"""Fixed notice copy. Operational facts are never translated or inferred by a model."""

COPY = {
    "en": {
        "notice": "Community notice",
        "regular": "Regular program",
        "demo": "Fictional demonstration",
        "update": "An update for your next visit",
        "cancel": "These sessions are canceled",
        "ended_heading": "Please check before your next visit",
        "affected": "Affected sessions",
        "previous": "Previous temporary arrangement",
        "confirmed": "Last confirmed by the program coordinator",
        "demo_confirmed": "Last confirmed by the demo coordinator",
        "download": "Download printable notice",
        "skip": "Skip to notice",
        "share": "One link. The latest confirmed details.",
        "share_help": "Share this page with someone who attends. No account needed.",
        "link": "Permanent notice link",
        "qr": "QR code for this permanent notice link",
        "demo_footer": "Demonstration workspace. Program details are entered for testing and are not a verified real service listing.",
        "footer": "Published by the program organization. Please use the contact instructions to confirm details before visiting.",
        "baseline": "Regular program details",
        "unpublished": "No temporary update has been published. Confirm current details with the organization.",
        "draft": "DRAFT PREVIEW — NOT PUBLISHED",
        "check_link": "Check this permanent link before your next visit:",
        "print_limit": "A new file does not replace previously printed copies. HTML is the primary accessible notice.",
        "relocation": "Temporary venue change",
        "cancellation": "Session cancellation",
        "time_change": "Session time change",
        "active": "Only the listed sessions are affected",
        "ended": "This arrangement has ended",
        "message": "Applies only to the sessions listed below. Other activities are unchanged.",
        "fallback": "This temporary arrangement has ended. Details for future sessions need confirmation.",
    },
    "es": {
        "notice": "Aviso comunitario",
        "regular": "Programa habitual",
        "demo": "Demostración ficticia",
        "update": "Información para su próxima visita",
        "cancel": "Estas sesiones están canceladas",
        "ended_heading": "Confirme los detalles antes de su próxima visita",
        "affected": "Sesiones afectadas",
        "previous": "Disposición temporal anterior",
        "confirmed": "Última confirmación por la persona responsable del programa",
        "demo_confirmed": "Última confirmación por la persona responsable de la demostración",
        "download": "Descargar aviso para imprimir",
        "skip": "Ir al aviso",
        "share": "Un enlace con los últimos detalles confirmados.",
        "share_help": "Comparta esta página con alguien que asista. No se necesita una cuenta.",
        "link": "Enlace permanente del aviso",
        "qr": "Código QR del enlace permanente de este aviso",
        "demo_footer": "Espacio de demostración. Los datos del programa son de prueba y no constituyen una oferta de servicios verificada.",
        "footer": "Publicado por la organización responsable del programa. Use las instrucciones de contacto para confirmar los detalles antes de acudir.",
        "baseline": "Detalles habituales del programa",
        "unpublished": "No se ha publicado ningún cambio temporal. Confirme los detalles actuales con la organización.",
        "draft": "VISTA PREVIA — NO PUBLICADA",
        "check_link": "Consulte este enlace antes de su próxima visita:",
        "print_limit": "Un archivo nuevo no sustituye las copias ya impresas. La página HTML es el aviso accesible principal.",
        "relocation": "Cambio temporal de lugar",
        "cancellation": "Cancelación de sesiones",
        "time_change": "Cambio de horario de las sesiones",
        "active": "Solo se ven afectadas las sesiones indicadas",
        "ended": "Esta disposición temporal ha finalizado",
        "message": "Este cambio se aplica solo a las sesiones indicadas a continuación. Las demás actividades no cambian.",
        "fallback": "Esta disposición temporal ha finalizado. Los detalles de las próximas sesiones aún deben confirmarse.",
    },
}
MONTHS_ES = (
    "enero",
    "febrero",
    "marzo",
    "abril",
    "mayo",
    "junio",
    "julio",
    "agosto",
    "septiembre",
    "octubre",
    "noviembre",
    "diciembre",
)
